---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.1

suites:
  - name: example_resource
    run_list:
      - recipe[example_resource_test::integration]
